jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Cerad\Bundle\AccountBundle\Entity\AccountUser: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    
        fos_userbundle:
            id: fos_user.user_provider.username_email
            
        cerad_account_user_provider:
            id: cerad_account.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            pattern:   ^/
            
            anonymous: ~
            
            cerad_janrain:
                provider:            cerad_account_user_provider
                add_path:            cerad_janrain_add
                check_path:          cerad_janrain_check
                login_path:          cerad_janrain_login
                register_path:       fos_user_registration_register
                default_target_path: fos_user_profile_show
                rpx_api_key:        %cerad_janrain_rpx_api_key%
            
            form_login:
                provider:            fos_userbundle
                check_path:          fos_user_security_check
                login_path:          fos_user_security_login
                default_target_path: fos_user_profile_show
                csrf_provider:       form.csrf_provider
               
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
 
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
